package:
  name: pip
  version: "1.5.6_dev"

source:
  git_url: git@github.com:pypa/pip.git
  git_tag: develop

build:
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pip = pip:main
    #
    # Would create an entry point called pip that calls pip.main()

    - pip=pip:main
    - pip-2.7=pip:main [py27]
    - pip-2.6=pip:main [py26]
    - pip-3.3=pip:main [py33]

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pip._vendor
    - pip.commands
    - pip.compat
    - pip.req
    - pip.utils
    - pip.vcs
    - pip

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - pip --help
    - pip-2.7 --help [py27]
    - pip-2.6 --help [py26]
    - pip-3.3 --help [py33]

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.pip-installer.org
  license: MIT License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
